优化启动脚本

diff --git a/mariadb/docker-entrypoint b/mariadb/docker-entrypoint
--- a/mariadb/docker-entrypoint
+++ b/mariadb/docker-entrypoint
@@ -9,49 +9,37 @@ if [ "${1#-}" != "$1" ]; then
 fi
 
 if [ "$1" = "mysqld" ]; then
-
-    if [ -z "$DATADIR" ]; then
-        DATADIR=/data
-    fi
+    DATADIR=/data
 
     if [ -d "$DATADIR/mysql" ]; then
-        echo "[info] MySQL directory already present, skipping creation"
-        chown -R mysql:mysql "$DATADIR"
+        echo "[INFO] MySQL directory already present, skipping creation"
     else
-        echo "[info] MySQL data directory not found, creating initial DBs"
+        echo "[INFO] MySQL data directory not found, creating initial DBs"
 
-        mkdir -p "$DATADIR"
-
-        chown mysql:mysql -R "$DATADIR"
-
-        mysql_install_db --user=mysql --datadir="$DATADIR" # > /dev/null
+        mysql_install_db --user=mysql --datadir="$DATADIR"
 
         "$@" --skip-networking --socket=/var/run/mysqld/mysqld.sock &
         pid="$!"
 
         mysql="mysql -hlocalhost --protocol=socket -uroot --socket=/var/run/mysqld/mysqld.sock"
-        
+
         for i in {30..0}; do
-            if echo 'SELECT 1' | $mysql &> /dev/null; then
+            if echo 'SELECT 1' | $mysql &>/dev/null; then
                 break
             fi
-            echo '[info] MySQL init process in progress...'
+            echo '[INFO] MySQL init process in progress...'
             sleep 1
         done
 
         if [ "$i" = 0 ]; then
-            echo >&2 '[info] MySQL init process failed.'
+            echo >&2 '[ERROR] MySQL init process failed.'
             exit 1
         fi
 
         if [ -z "$MYSQL_ROOT_PASSWORD" ]; then
             MYSQL_ROOT_PASSWORD="$(pwgen 16 1)"
-            echo "[info] Generatwd MySQL root Password: $MYSQL_ROOT_PASSWORD"
+            echo "[INFO] Generated MySQL root Password: $MYSQL_ROOT_PASSWORD"
         fi
-
-        MYSQL_DATABASE=${MYSQL_DATABASE:-""}
-        MYSQL_USER=${MYSQL_USER:-""}
-        MYSQL_PASSWORD=${MYSQL_PASSWORD:-""}
 
         $mysql <<-EOF
     USE mysql;
@@ -59,48 +47,62 @@ if [ "$1" = "mysqld" ]; then
     SET PASSWORD FOR 'root'@'localhost'=PASSWORD('$MYSQL_ROOT_PASSWORD');
     GRANT ALL ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
     CREATE USER 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
-	GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;
+    GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;
     DROP DATABASE IF EXISTS test;
     FLUSH PRIVILEGES;
 EOF
+        if [ -n "$MYSQL_ROOT_PASSWORD" ]; then
+            mysql="$mysql -p$MYSQL_ROOT_PASSWORD"
+        fi
 
-        if [ ! -z "$MYSQL_ROOT_PASSWORD" ]; then
-			mysql="$mysql -p$MYSQL_ROOT_PASSWORD"
-		fi
+        MYSQL_DATABASE=${MYSQL_DATABASE:-""}
+        MYSQL_USER=${MYSQL_USER:-""}
+        MYSQL_PASSWORD=${MYSQL_PASSWORD:-$(pwgen 16 1)}
 
-        if [ ! -z "$MYSQL_DATABASE" ]; then
-            echo "[info] Creating database: $MYSQL_DATABASE"
+        if [ -n "$MYSQL_DATABASE" ]; then
+            echo "[INFO] Create database: $MYSQL_DATABASE"
             echo "CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;" | $mysql
-
             mysql="$mysql $MYSQL_DATABASE"
         fi
 
-        if [ ! -z "$MYSQL_USER" -a "$MYSQL_PASSWORD" ]; then
-            echo "[info] Creating user: $MYSQL_USER with password $MYSQL_PASSWORD"
+        if [ -n "$MYSQL_USER" ] -a [ -n "$MYSQL_PASSWORD" ]; then
+            echo "[INFO] Create user $MYSQL_USER with password $MYSQL_PASSWORD"
             echo "CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD' ;" | $mysql
 
-            if [ "$MYSQL_DATABASE" ]; then
+            if [ -n "$MYSQL_DATABASE" ]; then
+                echo "[INFO] Grant user $MYSQL_USER all permissions to database $MYSQL_DATABASE"
                 echo "GRANT ALL ON \`$MYSQL_DATABASE\`.* TO '$MYSQL_USER'@'%' ;" | $mysql
             fi
         fi
 
-        echo
-        for f in /docker-entrypoint-initdb.d/*; do
-            case "$f" in
-                *.sql)    echo "$0: running $f"; $mysql < "$f"; echo ;;
-                *.sql.gz) echo "$0: running $f"; gunzip -c "$f" | $mysql; echo ;;
-                *)        echo "$0: ignoring $f" ;;
-            esac
+        if [ -d "/import" ]; then
             echo
-        done
+            for f in /import/*; do
+                case "$f" in
+                *.sql)
+                    echo "$0: running $f"
+                    $mysql <"$f"
+                    echo
+                    ;;
+                *.sql.gz)
+                    echo "$0: running $f"
+                    gunzip -c "$f" | $mysql
+                    echo
+                    ;;
+                *)
+                    echo "$0: ignoring $f" ;;
+                esac
+                echo
+            done
+        fi
 
-        if ! kill -s TERM "$pid" || ! wait "$pid" ; then
-            echo >&2 'MySQL init process failed.'
+        if ! kill -s TERM "$pid" || ! wait "$pid"; then
+            echo >&2 '[ERROR] MySQL init process failed.'
             exit 1
         fi
 
         echo
-        echo 'MySQL init process done. Ready for start up.'
+        echo '[INFO] MySQL init process done. Ready for start up.'
         echo
     fi
 fi
